<a href="https://colab.research.google.com/github/JH627/LA2/blob/main/%5B00%5D%EC%8B%A4%EC%8A%B5Zero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
print("Hello World!")

Hello World!


### 라이브러리 패키지(로드)

In [7]:
import numpy as np

#### 2. 벡터, 행렬 연산, 그래프 그리기
#### 프린트

In [11]:
def print_val(x):
  print("Type:", type(x))
  print("Shape:", x.shape)
  print("값:\n", x)
  print(" ")

In [13]:
x = np.array([1, 2, 3])
print_val(x)

x[0] = 5
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [5 2 3]
 


In [15]:
y = np.array([[1, 2, 3], [4, 5, 6]])
print_val(y)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값:
 [[1 2 3]
 [4 5 6]]
 


In [16]:
a = np.zeros((2, 2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[0. 0.]
 [0. 0.]]
 


In [18]:
a = np.ones((3, 2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


In [21]:
a = np.eye(3, 3)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


In [23]:
a = np.random.random((4, 4))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[0.7319988  0.0050497  0.96629087 0.62744391]
 [0.35947351 0.91359763 0.19900996 0.376992  ]
 [0.22155187 0.80621368 0.56697755 0.37232144]
 [0.2738593  0.61696211 0.00694284 0.01516438]]
 


In [24]:
a = np.random.randn(4, 4)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[ 0.24841348 -1.06512343  0.36457446  1.2982037 ]
 [ 0.21367579  1.05155922  0.56809707  0.19770115]
 [ 1.46349104 -0.35555485  0.57421078 -0.7188891 ]
 [ 0.2471773   0.99246585 -1.18075147 -0.26012082]]
 


In [27]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
print(m1)
print(m1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [28]:
print(np.sum(m1))
print(np.sum(m1, axis = 0))
print(np.sum(m1, axis = 1))

21
[5 7 9]
[ 6 15]
